### ISSUE TITLE
Podcast that fails mongo validation

### ISSUE THREAD

**Issue by djdembeck** [laxamentumtech/audnexus#257]
> {"method":"GET","url":"/books/B08GC9K8XJ","hostname":"api.audnex.us","remoteAddress":"10.0.1.5","remotePort":48132},"res":{"statusCode":500},"err":{"type":"MongoServerError","message":"Document failed validation","stack":"MongoServerError: Document failed validation\n at /app/node_modules/mongodb/lib/operations/insert.js:51:33\n at /app/node_modules/mongodb/lib/cmap/connection_pool.js:273:25\n at handleOperationResult (/app/node_modules/mongodb/lib/sdam/server.js:363:9)\n at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:474:9)\n at MessageStream.emit (node:events:520:28)\n at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:108:16)\n at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:28:9)\n at writeOrBuffer (node:internal/streams/writable:389:12)\n at _write (node:internal/streams/writable:330:10)\n at MessageStream.Writable.write (node:internal/streams/writable:334:10)","index":0,"code":121,"errInfo":{"failingDocumentId":"621ed0f76742d31b21ab04b1","details":{"operatorName":"$jsonSchema","schemaRulesNotSatisfied":[{"operatorName":"properties","propertiesNotSatisfied":[{"propertyName":"genres","details":[{"operatorName":"items","reason":"At least one item did not match the sub-schema","itemIndex":0,"details":[{"operatorName":"type","specifiedAs":{"type":"object"},"reason":"type did not match","consideredValue":null,"consideredType":"null"}]}]}]}]}}},"msg":"Document failed validation"}

`B08GC9K8XJ`

**Comment by djdembeck** [comment]
Another one is `B095T2L8G6`. I think all that is necessary is to remove `runtime_length_min` as a required key if podcast properties are present.
